The code below is from this tutorial:
https://www.geeksforgeeks.org/q-learning-in-python/

In [1]:
# Defining the environment
import numpy as np

# States in the grid world
#   wtf is a grid world
n_states = 16 

# Possible Actions (up, down, left, right)
n_actions = 4

# Goal State
#   wtf is this??? We have a goal for what state we end up in? 
#   What is it out of???
goal_state = 15

# Q-table initialized with zeros
Q_table = np.zeros((n_states, n_actions))

In [2]:
# Setting up hyperparameters

learning_rate = 0.8
discount_factor = 0.95
exploration_prob = 0.2
epochs = 1000

# I only know what two of these parameters are.
# The other two seem specific to this concept

Up next is implimenting the Q-learning Alg. We're going to go through multiple epochs and selecting actions based on the epsilon-greedy strategy. What's the epsilon-greedy strategy? No idea! The human brain is not built for memory, therefor I cannot remember the big chonky words I read 10 minutes ago. 

Anyway, we also update the Q-values based on rewards and transition to the next step

In [3]:
# Q learning Alg

for epoch in range(epochs):
    # starting from a random state
    current_state = np.random.randint(0, n_states)

    while current_state != goal_state:
        #   Ok I think I kinda get it now
        # Choose action with epsilon-greedy strategy
        if np.random.rand() < exploration_prob:
            # Explore
            #   wtf do you mean explore???
            action = np.random.randint(0, n_actions)
        else:
            # Exploit
            #   ??????
            #   What are we exploiting????
            action = np.argmax(Q_table[current_state])

        # Simulate environment / move to the next state
        #   uhhhhhh
        # Simply put, move to the next state
        #   None of this is simple.
        #       Ok now that I have things indented correctly 
        #       things make more sense
        next_state = (current_state + 1) % n_states
        #   Wow it's been a hot second since I've used modulo

        # define simple reward function
        reward = 1 if next_state == goal_state else 0

        # Update the Q-learning update rule
        #   Yep those words certainly made sense
        Q_table[current_state, action] += learning_rate * (
            reward + discount_factor * np.max(
                Q_table[next_state]) - Q_table[current_state, action])
        
        # move to the next state
        current_state = next_state
        #   It is WILD seeing such a short line of code 
        #   after that chonky af math equation

In [4]:
#   Ok there's no way that last code block is supposed to be able 
#   to be ran in .1 secconds

# After training the Q-table should represent the learned Q-Values
print("Learned Q-table:")
print(Q_table)

Learned Q-table:
[[0.48767498 0.48751286 0.48751892 0.48377358]
 [0.50923535 0.51330923 0.51334077 0.51334208]
 [0.54036009 0.54036009 0.54036009 0.54035981]
 [0.56880009 0.56880009 0.56880008 0.56880009]
 [0.59873694 0.59873541 0.59873541 0.59873663]
 [0.63024941 0.63024941 0.63024941 0.63024941]
 [0.66342043 0.66342043 0.66342043 0.66342043]
 [0.6983373  0.6983373  0.6983373  0.6983373 ]
 [0.73509189 0.73509189 0.73509189 0.73509189]
 [0.77378094 0.77378094 0.77378094 0.77378094]
 [0.81450625 0.81450625 0.81450625 0.81450625]
 [0.857375   0.857375   0.857375   0.857375  ]
 [0.9025     0.9025     0.9025     0.9025    ]
 [0.95       0.95       0.95       0.95      ]
 [1.         1.         1.         1.        ]
 [0.         0.         0.         0.        ]]


Ok so what did I accomplish though? This is saying that it produces a model to address certain issues, but we didn't create a model. Only a table. Is this like... preliminary data processing then?

Looks like that's a no. It's used to build neural networks, but it in and of itself is not a neural network

I need a use case to visualize it. Numbers only mean so much.